apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: knative-eventing.packages.kadras.io.1.8.4+kadras.1
spec:
  licenses:
  - Apache 2.0
  refName: knative-eventing.packages.kadras.io
  releaseNotes: https://github.com/knative/eventing/releases
  releasedAt: "2023-01-12T23:29:53Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-knative-eventing@sha256:7758f1009ff9aa4918ca516b8502ebe327e14f3ad5cabc97d1c186f2fbb7e58d
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        default_broker:
          additionalProperties: false
          description: Configuration for the default in-memory broker
          properties:
            enabled:
              default: false
              description: Whether to install the default in-memory broker
              type: boolean
            namespace:
              default: default
              description: The namespace where to install the default broker
              type: string
          type: object
      type: object
  version: 1.8.4+kadras.1
