apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cert-manager.packages.kadras.io.1.10.0+kadras.2
spec:
  licenses:
  - Apache 2.0
  refName: cert-manager.packages.kadras.io
  releaseNotes: https://github.com/jetstack/cert-manager/releases
  releasedAt: "2022-11-13T19:58:08Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
          - --kube-api-qps=50
          - --kube-api-burst=100
      fetch:
      - imgpkgBundle:
          image: ghcr.io/arktonix/package-for-cert-manager@sha256:074da91e68a85ad579cbd06c279bad63257368301ce3759c650c243c1b5aa85c
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        namespace:
          default: cert-manager
          description: The namespace in which to deploy Cert Manager
          type: string
      type: object
  version: 1.10.0+kadras.2
