apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cert-manager.packages.kadras.io.1.10.1
spec:
  licenses:
  - Apache 2.0
  refName: cert-manager.packages.kadras.io
  releaseNotes: https://github.com/jetstack/cert-manager/releases
  releasedAt: "2022-11-23T19:46:49Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
          - --kube-api-qps=50
          - --kube-api-burst=100
      fetch:
      - imgpkgBundle:
          image: ghcr.io/arktonix/package-for-cert-manager@sha256:14dd64e02208c5baabd29c3c1e02472e3f91890dc8b3d81384d0bee57db49b53
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        namespace:
          default: cert-manager
          description: The namespace in which to deploy Cert Manager
          type: string
      type: object
  version: 1.10.1
