apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cert-manager.packages.kadras.io.1.10.2
spec:
  licenses:
  - Apache 2.0
  refName: cert-manager.packages.kadras.io
  releaseNotes: https://github.com/jetstack/cert-manager/releases
  releasedAt: "2023-01-10T19:50:35Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
          - --kube-api-qps=50
          - --kube-api-burst=100
      fetch:
      - imgpkgBundle:
          image: ghcr.io/arktonix/package-for-cert-manager@sha256:cc905cfd171d29d3cd792d4e265dd78cde09e6f7159f9863acfc93339b1dfb3a
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        namespace:
          default: cert-manager
          description: The namespace in which to deploy Cert Manager
          type: string
      type: object
  version: 1.10.2
