apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: spring-boot-conventions.packages.kadras.io.0.1.1
spec:
  licenses:
  - Apache 2.0
  refName: spring-boot-conventions.packages.kadras.io
  releaseNotes: https://github.com/arktonix/spring-boot-conventions
  releasedAt: "2022-10-31T20:38:25Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/arktonix/package-for-spring-boot-conventions@sha256:9f2a483556d8c9a9d894bbbd13ad2948f5901d32cad87bd7f5a2e456cd391d3c
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        namespace:
          default: spring-boot-conventions
          description: The namespace where to install the Spring Boot Conventions
          type: string
        resources:
          additionalProperties: false
          description: Resource configuration for the Convention Server
          properties:
            limits:
              additionalProperties: false
              description: Resource limits
              properties:
                cpu:
                  default: 100m
                  description: CPU limits
                  type: string
                memory:
                  default: 256Mi
                  description: Memory limits
                  type: string
              type: object
            requests:
              additionalProperties: false
              description: Resource requests
              properties:
                cpu:
                  default: 100m
                  description: CPU requests
                  type: string
                memory:
                  default: 20Mi
                  description: Memory requests
                  type: string
              type: object
          type: object
      type: object
  version: 0.1.1
