apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cartographer-blueprints.packages.kadras.io.0.1.1
spec:
  refName: cartographer-blueprints.packages.kadras.io
  releasedAt: "2022-10-04T09:00:23Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/arktonix/cartographer-blueprints@sha256:02e93af08580308e0697b9716d2f6aa83925a55300b717b079dcf16090998a16
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        excluded_blueprints:
          default: []
          description: A list of blueprints and manifests to esclude from being applied.
          items:
            default: ""
            type: string
          type: array
      type: object
  version: 0.1.1
