apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cartographer-blueprints.packages.kadras.io.0.1.0
spec:
  refName: cartographer-blueprints.packages.kadras.io
  releasedAt: "2022-09-29T21:56:00Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/arktonix/cartographer-blueprints@sha256:388156fc3c4cff7dd6e3b72643c366377b9303d1421c5498b0aaaeed5902607a
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        excluded_blueprints:
          default: []
          description: A list of blueprints and manifests to esclude from being applied.
          items:
            default: ""
            type: string
          type: array
      type: object
  version: 0.1.0
