apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cartographer-blueprints.packages.kadras.io.0.2.0
spec:
  refName: cartographer-blueprints.packages.kadras.io
  releasedAt: "2022-10-26T19:45:11Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/arktonix/cartographer-blueprints@sha256:b03ad09707b3ebb5de2f3657bfc1e43e98da3e114bb7c67133509d2ea133114b
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        excluded_blueprints:
          default: []
          description: A list of blueprints and manifests to esclude from being applied.
          items:
            default: ""
            type: string
          type: array
      type: object
  version: 0.2.0
