apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: kpack-dependencies.packages.kadras.io.0.2.0
spec:
  refName: kpack-dependencies.packages.kadras.io
  releasedAt: "2022-10-25T21:05:46Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/arktonix/kpack-dependencies@sha256:6b95a9dda1e836a8b976a0be4e1e6f997731d86bea5d245fddbfd25b7b347d32
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        kp_default_repository:
          default: ""
          description: The OCI registry where to publish builder images. The same
            as configured in kpack.
          type: string
      type: object
  version: 0.2.0
