apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: kpack-dependencies.packages.kadras.io.0.3.1
spec:
  refName: kpack-dependencies.packages.kadras.io
  releasedAt: "2022-11-25T23:44:12Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/arktonix/kpack-dependencies@sha256:c7bc98f1f63e0879f3896fa008fbbdc24a832de7ebd3b40f8a8b56bafc6d7aba
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        kp_default_repository:
          default: ""
          description: The OCI registry where to publish builder images. The same
            as configured in kpack.
          type: string
      type: object
  version: 0.3.1
