apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: kpack-dependencies.packages.kadras.io.0.3.2
spec:
  refName: kpack-dependencies.packages.kadras.io
  releasedAt: "2022-11-28T18:44:40Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/arktonix/kpack-dependencies@sha256:6548de6f924a10c11236eea2b988b95b5702486ca91378f764422b68db25ee97
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        kp_default_repository:
          default: ""
          description: The OCI registry where to publish builder images. The same
            as configured in kpack.
          type: string
      type: object
  version: 0.3.2
