apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: fluxcd-source-controller.packages.kadras.io.0.32.1+kadras.2
spec:
  licenses:
  - Apache 2.0
  refName: fluxcd-source-controller.packages.kadras.io
  releaseNotes: https://github.com/fluxcd/source-controller/releases
  releasedAt: "2022-12-13T21:43:54Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/arktonix/package-for-fluxcd-source-controller@sha256:505bca54e3b3c22607c2e3ad22622334828348fb761cdd50adb1bee5f7d9c21b
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        namespace:
          default: source-system
          description: The namespace where to install FluxCD Source Controller
          type: string
        proxy:
          additionalProperties: false
          description: Configure proxy support
          properties:
            http_proxy:
              default: ""
              description: The HTTP proxy URL
              type: string
            https_proxy:
              default: ""
              description: The HTTPS proxy URL
              type: string
            no_proxy:
              default: ""
              description: For which domains the proxy should not be used
              type: string
          type: object
        resources:
          additionalProperties: false
          description: Resource configuration for the source-controller Deployment
          properties:
            limits:
              additionalProperties: false
              properties:
                cpu:
                  default: 1000m
                  type: string
                memory:
                  default: 1Gi
                  type: string
              type: object
          type: object
        service_port:
          default: 80
          description: Port configuration for the source-controller Service
          type: integer
      type: object
  version: 0.32.1+kadras.2
