apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: namespace-setup.packages.kadras.io.0.1.1
spec:
  refName: namespace-setup.packages.kadras.io
  releasedAt: "2022-11-01T17:53:33Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/arktonix/namespace-setup@sha256:8a95e7f23fa9698013c1f1a472230787d0ac6d1e9384091dd50a5c0b3760d77f
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        gitops:
          additionalProperties: false
          description: Configuration to access the Git repositories used in the GitOps
            workflows
          properties:
            password:
              default: ""
              description: The password for the Git server used in the GitOps workflows
              type: string
            server:
              default: https://github.com
              description: The Git server hosting the Git repositories used in the
                GitOps workflows
              type: string
            username:
              default: ""
              description: The username for the Git server used in the GitOps workflows
              type: string
          type: object
        namespaces:
          default: []
          description: Configuration for developer namespaces
          items:
            additionalProperties: false
            description: Details about the namespace to configure
            properties:
              exists:
                default: false
                type: boolean
              name:
                default: ""
                type: string
            type: object
          type: array
        registry:
          additionalProperties: false
          description: Configuration to access the OCI registry where the Kadras packages
            are stored
          properties:
            password:
              default: ""
              description: The password for the OCI registry server where the Kadras
                packages are stored
              type: string
            server:
              default: ""
              description: The OCI registry server where the Kadras packages are stored
              type: string
            username:
              default: ""
              description: The username for the OCI registry server where the Kadras
                packages are stored
              type: string
          type: object
      type: object
  version: 0.1.1
