apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cartographer-delivery.packages.kadras.io.0.1.1
spec:
  refName: cartographer-delivery.packages.kadras.io
  releasedAt: "2022-10-04T12:14:48Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/arktonix/cartographer-delivery@sha256:ae1240360cc97218b667070c2c470e693bc835a890e72e524c4693a7501ccc32
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        delivery_chain:
          default: basic
          description: The type of delivery chain to use when deploying workloads
          type: string
        git_implementation:
          default: go-git
          description: The Git implementation used by Flux
          type: string
        service_account:
          default: default
          description: The ServiceAccount used by the supply chain
          type: string
      type: object
  version: 0.1.1
