apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: cartographer-golden-path-web.packages.kadras.io
spec:
  categories:
  - ci/cd
  - golden paths
  - platform engineering
  displayName: cartographer-golden-path-web
  longDescription: Cartographer supply chains used to build a golden path for web
    applications and functions.
  maintainers:
  - name: Thomas Vitale
  providerName: Arktonix
  shortDescription: Golden path for web applications and functions.
